config/routes.rb
Parknet::Application.routes.draw do

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  devise_for :users

	root :to => "staff_access#login"

	get "staff_registration/registration"
	get "browse_programs/show"
	get "customer_access/browse"
	match 'customer/login', :to => 'customer_access#login'
	match 'staff_menu', :to => 'staff_sessions#menu'
	get "log_in" => "staff_sessions#new", :as => "log_in"
	get "staff_menu" => "staff_sessions#menu", :as => "staff_menu"
	get "staff_access/select_location"
	get "customer_access/menu"
	get "customer_access/logout"
	get "online_registration/view_basket"
	get "online_registration/waiver"
	get "online_registration/checkout"
	get "online_registration/take_payment"
	get "online_registration/no_payment"
	get "static_pages/home"
	get "static_pages/help"
	get "facilities/list"
	get "facility_types/list"
	get "funds/list"
	get "staff_users/list"
	get "gl_accounts/list"
	get "season_titles/list"
	get "seasons/list"
	get "brochure_sections/list"
	get "brochure_sections/program_list"
	get "brochure_subsections/list"
	get "programs/list"
	get "programs/browse"
	get "class_sessions/list"
	get "programs/edit"
	get "accounts/list"
	get "accounts/edit"
	get "accounts/search"
	get "refunds/process_refunds"
	get "membership1_level_ones/list"
	post "maintain_program" => "programs#edit", :as => "maintain_program"
	get "class_sessions/list_per_program"
	post "new_class_session" => "class_session#new", :as => "new_class_session"
	get "staff_registration/lookup_account"
	get "payments/take_payment"
	match 'staff', :to => 'staff_access#menu'
	match 'customer', :to => 'customer_access#menu'
	get "class_sessions/edit"
	get "customers/add_member"
	get "customers/add_head_of_household"
	get "online_registration/show"
	get 'staff_membership_sales/update_level_two', :as => 'update_level_two'
	get 'staff_membership_sales/update_level_three', :as => 'update_level_three'
	get 'staff_membership_sales/update_term', :as => 'update_term'
	get 'staff_membership_sales/update_fees', :as => 'update_fees'
	get 'registrations/update_programs', :as => 'update_programs'
	get 'registrations/update_class_sessions', :as => 'update_class_sessions'
	get "accounting_transactions/select_gl_report_date"
	get "payments/select_daily_cash_balance_report_date"
	resources :facilities
	resources :funds
	resources :gl_accounts
	resources :staff_users
	resources :season_titles
	resources :seasons
	resources :brochure_sections
	resources :brochure_subsections
	resources :programs
	resources :class_sessions
	resources :class_session_fees
	resources :staff_sessions
	resources :accounts
	resources :customers
	resources :customer_access
	resources :payments
	resources :charges
	resources :online_registration
	resources :refunds
	resources :facility_types
	resources :membership_level_ones
	resources :membership_level_twos
	resources :membership_level_threes
	resources :memberships
	resources :membership_terms
	resources :membership_scans
	
  

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/headshots_controller.rb
class HeadshotsController < ApplicationController
	
	helper :headshot
	
	layout "staff"
	
	before_filter :confirm_logged_in
	
	def headshot_post_save
		@customer = current_agency.customers.find(params[:id])
		@customer.headshot_photo = params[:photo]
		if @customer.update_attributes(params[:customer])
			redirect_to(:action => 'edit', :controller => 'accounts', :id => @customer.account_id)
		else
			render('edit')
		end	
	end
	
	def index
		@customer = current_agency.customers.find(params[:id])
	end
end

app/views/headshots/index.html.erb
<h3>Take Photo for <%= @customer.first_name %> <%= @customer.last_name %></h3>


<%= headshot_default_config(Rails.application.config.session_options[:key], headshot_capture_path, :on_complete => "customCameraHooks.onComplete") %>


       <%= headshot_camera %>
    

        <br/><br/>

        <button name="button" onclick="headshotHandlers.snap()" type="submit">Snap</button>
        <button name="button" onclick="headshot.configure()" type="submit">Configure</button>
		
<span id="photos"></span>	
	
<%= form_tag({:controller => 'headshots', :action => 'headshot_post_save'}, {:id => 'customer_photo'}) do -%>
	<%= hidden_field_tag 'id', @customer.id %>
	<%= submit_tag "Accept Selected Photo" %>
<% end %>


<script language="JavaScript">
  var customCameraHooks = {
    onComplete: function(response) {
		var obj = JSON.parse(response);
		var url = obj.url;
		var split_url = url.split("_");
		var last = split_url.pop();
		var penultimate = split_url.pop();
		//console.log("<img src=\"/headshots_images/headshot_capture_" + penultimate + "_" + last + "\">");
		// example: {"status":"Success","message":"Headshot saved.","url":"http://localhost:3000/headshots_custom/headshot_custom_3365_1379649240.jpg"}
		headshot.reset(); // Reset the camera.
		$('#photos').html("<img src=\"/headshots_images/headshot_capture_"+ penultimate + "_" + last + "\">");
		$('#customer_photo').append($('<input type="hidden" name="photo" />').val("headshot_capture_" + penultimate + "_" + last));
    }
  };
</script>